Repository WeAreRoommies/Roomie-iOS, pull requests merged in 2025-06, with the labels that each got.

#186 [fix/#184] 관심지역 위치 설정 바텀시트 UI 수정
  Roomie/Roomie/Presentation/Home/View/LocationSearchSheetView.swift
  Roomie/Roomie/Presentation/Home/ViewController/HomeViewController.swift
  Roomie/Roomie/Presentation/Home/ViewController/LocationSearchViewController.swift
Labels: ✂️ fix, 🍥 hyunsoo

#187 [refactor/#182] 소셜 타입 적용, Toast 수정
  Roomie/Roomie/Application/SceneDelegate.swift
  Roomie/Roomie/Global/Enums/SocialType.swift
  Roomie/Roomie/Global/Enums/ToastType.swift
  Roomie/Roomie/Global/Security/Interceptor.swift
  Roomie/Roomie/Global/Utils/Toast.swift
  Roomie/Roomie/Presentation/OnBoarding/ViewController/LoginViewController.swift
  Roomie/Roomie/Presentation/OnBoarding/ViewModel/LoginViewModel.swift
Labels: 🧤 refactor, 🍞 seungwon

#190 [feat/#181] 회원 정보 수정 뷰 구현 및 API 연결
  Roomie/Roomie/Global/Components/DatePickerView.swift
  Roomie/Roomie/Global/Components/MyAccountWhiteButton.swift
  Roomie/Roomie/Global/Components/RoomieHalfButton.swift
  Roomie/Roomie/Global/Components/RoomieTextField.swift
  Roomie/Roomie/Global/Enums/Gender.swift
  Roomie/Roomie/Global/Utils/KeyboardConstraintHandler.swift
  Roomie/Roomie/Network/DTO/Maps/MapRequestDTO.swift
  Roomie/Roomie/Network/DTO/Maps/MapResponseDTO.swift
  Roomie/Roomie/Network/DTO/Users/BirthDateRequestDTO.swift
  Roomie/Roomie/Network/DTO/Users/BirthDateResponseDTO.swift
  Roomie/Roomie/Network/DTO/Users/GenderRequestDTO.swift
  Roomie/Roomie/Network/DTO/Users/GenderResponseDTO.swift
  Roomie/Roomie/Network/DTO/Users/NameRequestDTO.swift
  Roomie/Roomie/Network/DTO/Users/NameResponseDTO.swift
  Roomie/Roomie/Network/DTO/Users/NicknameRequestDTO.swift
  Roomie/Roomie/Network/DTO/Users/NicknameResponseDTO.swift
  Roomie/Roomie/Network/DTO/Users/PhoneNumberRequestDTO.swift
  Roomie/Roomie/Network/DTO/Users/PhoneNumberResponseDTO.swift
  Roomie/Roomie/Network/Service/MapsService.swift
  Roomie/Roomie/Network/Service/MyAccountService.swift
  Roomie/Roomie/Network/Service/MyPageService.swift
  Roomie/Roomie/Network/TargetType/MyAccountTargetType.swift
  Roomie/Roomie/Presentation/Map/ViewController/MapViewController.swift
  Roomie/Roomie/Presentation/MapFilter/Model/MapRequestModelBuilder.swift
  Roomie/Roomie/Presentation/MapFilter/ViewController/MapFilterViewController.swift
  Roomie/Roomie/Presentation/MyAccount/Component/MyAccountCellButton.swift
  Roomie/Roomie/Presentation/MyAccount/Component/MyAccountTypeView.swift
  Roomie/Roomie/Presentation/MyAccount/ServiceProtocol/MyAccountServiceProtocol.swift
  Roomie/Roomie/Presentation/MyAccount/View/BirthDateEditView.swift
  Roomie/Roomie/Presentation/MyAccount/View/GenderEditView.swift
  Roomie/Roomie/Presentation/MyAccount/View/MyAccountView.swift
  Roomie/Roomie/Presentation/MyAccount/View/NameEditView.swift
  Roomie/Roomie/Presentation/MyAccount/View/NicknameEditView.swift
  Roomie/Roomie/Presentation/MyAccount/View/PhoneNumberEditView.swift
  Roomie/Roomie/Presentation/MyAccount/ViewController/BirthDateEditViewController.swift
  Roomie/Roomie/Presentation/MyAccount/ViewController/GenderEditViewController.swift
  Roomie/Roomie/Presentation/MyAccount/ViewController/MyAccountViewController.swift
  Roomie/Roomie/Presentation/MyAccount/ViewController/NameEditViewController.swift
  Roomie/Roomie/Presentation/MyAccount/ViewController/NicknameEditViewController.swift
  Roomie/Roomie/Presentation/MyAccount/ViewController/PhoneNumberEditViewController.swift
  Roomie/Roomie/Presentation/MyAccount/ViewModel/BirthDateEditViewModel.swift
  Roomie/Roomie/Presentation/MyAccount/ViewModel/GenderEditViewModel.swift
  Roomie/Roomie/Presentation/MyAccount/ViewModel/MyAccountViewModel.swift
  Roomie/Roomie/Presentation/MyAccount/ViewModel/NameEditViewModel.swift
  Roomie/Roomie/Presentation/MyAccount/ViewModel/NicknameEditViewModel.swift
  Roomie/Roomie/Presentation/MyAccount/ViewModel/PhoneNumberEditViewModel.swift
  Roomie/Roomie/Presentation/MyPage/Component/MyPageCellButton.swift
  Roomie/Roomie/Presentation/MyPage/Component/MyPageHeaderButton.swift
  Roomie/Roomie/Presentation/MyPage/ServiceProtocol/MyPageServiceProtocol.swift
  Roomie/Roomie/Presentation/MyPage/ViewController/MyAccountViewController.swift
  Roomie/Roomie/Presentation/MyPage/ViewController/MyPageViewController.swift
  Roomie/Roomie/Presentation/Tour/View/TourUserView.swift
Labels: 🛠️ feat, 🎂 suyeon
