Repository WeAreRoommies/Roomie-iOS, pull requests merged in 2025-01, with the labels that each got.

#2 [docs/#1] 깃 이그노어 및 템플릿 추가
  .github/ISSUE_TEMPLATE/이슈-템플릿.md
  .github/PULL_REQUEST_TEMPLATE.md
  .gitignore
  README.md
Labels: 📚 docs, 🎂 suyeon

#4 [setting/#3] 폴더링 및 기초 파일 추가
  Roomie/Roomie.xcodeproj/project.pbxproj
  Roomie/Roomie.xcodeproj/project.xcworkspace/contents.xcworkspacedata
  Roomie/Roomie/Application/AppDelegate.swift
  Roomie/Roomie/Application/SceneDelegate.swift
  Roomie/Roomie/Global/Base.lproj/LaunchScreen.storyboard
  Roomie/Roomie/Global/Base/BaseCollectionReusableView.swift
  Roomie/Roomie/Global/Base/BaseCollectionViewCell.swift
  Roomie/Roomie/Global/Base/BaseTableViewCell.swift
  Roomie/Roomie/Global/Base/BaseView.swift
  Roomie/Roomie/Global/Base/BaseViewController.swift
  Roomie/Roomie/Global/Components/.gitkeep
  Roomie/Roomie/Global/Enums/.gitkeep
  Roomie/Roomie/Global/Extensions/NSAttributedString+.swift
  Roomie/Roomie/Global/Extensions/UIButton+.swift
  Roomie/Roomie/Global/Extensions/UIFont+.swift
  Roomie/Roomie/Global/Extensions/UILabel+.swift
  Roomie/Roomie/Global/Extensions/UIStackView+.swift
  Roomie/Roomie/Global/Extensions/UITextField+.swift
  Roomie/Roomie/Global/Extensions/UIView+.swift
  Roomie/Roomie/Global/Info.plist
  Roomie/Roomie/Global/Resource/Assets.xcassets/AccentColor.colorset/Contents.json
  Roomie/Roomie/Global/Resource/Assets.xcassets/AppIcon.appiconset/Contents.json
  Roomie/Roomie/Global/Resource/Assets.xcassets/Contents.json
  Roomie/Roomie/Global/Utils/Observable.swift
  Roomie/Roomie/Global/Utils/ReuseIdentifiable.swift
  Roomie/Roomie/Global/Utils/Screen.swift
  Roomie/Roomie/Presentation/Home/View/HomeView.swift
  Roomie/Roomie/Presentation/Home/ViewController/HomeViewController.swift
  Roomie/Roomie/Presentation/Home/ViewModel/HomeViewModel.swift
Labels: 🧾 setting, 🎂 suyeon

#7 [add/#5] 라이브러리 설치
  README.md
  Roomie/Podfile
  Roomie/Podfile.lock
  Roomie/Roomie.xcodeproj/project.pbxproj
  Roomie/Roomie.xcworkspace/contents.xcworkspacedata
  Roomie/Roomie.xcworkspace/xcshareddata/swiftpm/Package.resolved
  Roomie/Roomie/Global/Info.plist
Labels: 📸 add, 🎂 suyeon

#9 [add/#8] Color Asset 추가
  Roomie/Roomie/Global/Resource/Colors.xcassets/Contents.json
  Roomie/Roomie/Global/Resource/Colors.xcassets/action/Contents.json
  Roomie/Roomie/Global/Resource/Colors.xcassets/action/action_error.colorset/Contents.json
  Roomie/Roomie/Global/Resource/Colors.xcassets/grayscale/Contents.json
  Roomie/Roomie/Global/Resource/Colors.xcassets/grayscale/grayscale_1.colorset/Contents.json
  Roomie/Roomie/Global/Resource/Colors.xcassets/grayscale/grayscale_10.colorset/Contents.json
  Roomie/Roomie/Global/Resource/Colors.xcassets/grayscale/grayscale_11.colorset/Contents.json
  Roomie/Roomie/Global/Resource/Colors.xcassets/grayscale/grayscale_12.colorset/Contents.json
  Roomie/Roomie/Global/Resource/Colors.xcassets/grayscale/grayscale_2.colorset/Contents.json
  Roomie/Roomie/Global/Resource/Colors.xcassets/grayscale/grayscale_3.colorset/Contents.json
  Roomie/Roomie/Global/Resource/Colors.xcassets/grayscale/grayscale_4.colorset/Contents.json
  Roomie/Roomie/Global/Resource/Colors.xcassets/grayscale/grayscale_5.colorset/Contents.json
  Roomie/Roomie/Global/Resource/Colors.xcassets/grayscale/grayscale_6.colorset/Contents.json
  Roomie/Roomie/Global/Resource/Colors.xcassets/grayscale/grayscale_7.colorset/Contents.json
  Roomie/Roomie/Global/Resource/Colors.xcassets/grayscale/grayscale_8.colorset/Contents.json
  Roomie/Roomie/Global/Resource/Colors.xcassets/grayscale/grayscale_9.colorset/Contents.json
  Roomie/Roomie/Global/Resource/Colors.xcassets/primary/Contents.json
  Roomie/Roomie/Global/Resource/Colors.xcassets/primary/primary.colorset/Contents.json
  Roomie/Roomie/Global/Resource/Colors.xcassets/primary/primary_dark1.colorset/Contents.json
  Roomie/Roomie/Global/Resource/Colors.xcassets/primary/primary_dark2.colorset/Contents.json
  Roomie/Roomie/Global/Resource/Colors.xcassets/primary/primary_light1.colorset/Contents.json
  Roomie/Roomie/Global/Resource/Colors.xcassets/primary/primary_light2.colorset/Contents.json
  Roomie/Roomie/Global/Resource/Colors.xcassets/primary/primary_light3.colorset/Contents.json
  Roomie/Roomie/Global/Resource/Colors.xcassets/primary/primary_light4.colorset/Contents.json
  Roomie/Roomie/Global/Resource/Colors.xcassets/primary/primary_light5.colorset/Contents.json
  Roomie/Roomie/Global/Resource/Colors.xcassets/secondary/Contents.json
  Roomie/Roomie/Global/Resource/Colors.xcassets/secondary/secondary.colorset/Contents.json
  Roomie/Roomie/Global/Resource/Colors.xcassets/secondary/secondary_light1.colorset/Contents.json
  Roomie/Roomie/Global/Resource/Colors.xcassets/secondary/secondary_light2.colorset/Contents.json
  Roomie/Roomie/Global/Resource/Colors.xcassets/secondary/secondary_light3.colorset/Contents.json
  Roomie/Roomie/Global/Resource/Colors.xcassets/transparent/Contents.json
  Roomie/Roomie/Global/Resource/Colors.xcassets/transparent/transp_gray12_10.colorset/Contents.json
  Roomie/Roomie/Global/Resource/Colors.xcassets/transparent/transp_gray12_50.colorset/Contents.json
  Roomie/Roomie/Global/Resource/Colors.xcassets/transparent/transp_gray12_60.colorset/Contents.json
  Roomie/Roomie/Global/Resource/Colors.xcassets/transparent/transp_gray1_30.colorset/Contents.json
  Roomie/Roomie/Global/Resource/Colors.xcassets/transparent/transp_gray1_60.colorset/Contents.json
Labels: 📸 add, 🍩 seungwon

#13 [feat/#12] 네비게이션 바 및 하단 메뉴 바 커스텀
  Roomie/Roomie/Application/SceneDelegate.swift
  Roomie/Roomie/Global/Base/BaseViewController.swift
  Roomie/Roomie/Global/Resource/Assets.xcassets/icn/btn_back.imageset/Contents.json
  Roomie/Roomie/Global/Resource/Assets.xcassets/icn/btn_back.imageset/btn_back.svg
  Roomie/Roomie/Global/Resource/Assets.xcassets/icn/icn_heart_line_24.imageset/Contents.json
  Roomie/Roomie/Global/Resource/Assets.xcassets/icn/icn_heart_line_24.imageset/icn_heart_line_24.svg
  Roomie/Roomie/Global/Resource/Assets.xcassets/icn/icn_inquire_24.imageset/Contents.json
  Roomie/Roomie/Global/Resource/Assets.xcassets/icn/icn_inquire_24.imageset/icn_inquire_24.svg
  Roomie/Roomie/Global/Resource/Assets.xcassets/icn/icn_map2_line_24.imageset/Contents.json
  Roomie/Roomie/Global/Resource/Assets.xcassets/icn/icn_map2_line_24.imageset/icn_map2_line_24.svg
  Roomie/Roomie/Global/Resource/Assets.xcassets/icn/icn_map_line_16.imageset/Contents.json
  Roomie/Roomie/Global/Resource/Assets.xcassets/icn/icn_map_line_16.imageset/icn_map_line_16.svg
  Roomie/Roomie/Global/Resource/Assets.xcassets/icn/icn_map_line_24.imageset/Contents.json
  Roomie/Roomie/Global/Resource/Assets.xcassets/icn/icn_map_line_24.imageset/icn_map_line_24.svg
  Roomie/Roomie/Presentation/Core/MainTabBarController.swift
  Roomie/Roomie/Presentation/Map/View/MapView.swift
  Roomie/Roomie/Presentation/Map/ViewController/MapViewController.swift
  Roomie/Roomie/Presentation/Map/ViewModel/MapViewModel.swift
  Roomie/Roomie/Presentation/MyPage/View/MyPageView.swift
  Roomie/Roomie/Presentation/MyPage/ViewController/MyPageViewController.swift
  Roomie/Roomie/Presentation/MyPage/ViewModel/MyPageViewModel.swift
Labels: 🛠️ feat, 🎂 suyeon

#15 [feat/#14] 지도 뷰 UI 구현
  Roomie/Roomie/Global/Extensions/UIFont+.swift
  Roomie/Roomie/Global/Protocol/ViewModelType.swift
  Roomie/Roomie/Global/Resource/Assets.xcassets/icn/icn_arrow_left_line_44.imageset/Contents.json
  Roomie/Roomie/Global/Resource/Assets.xcassets/icn/icn_arrow_left_line_44.imageset/icn_arrow_left_line_44.svg
  Roomie/Roomie/Global/Resource/Assets.xcassets/icn/icn_arrow_right_line_40.imageset/Contents.json
  Roomie/Roomie/Global/Resource/Assets.xcassets/icn/icn_arrow_right_line_40.imageset/icn_arrow_right_line_40.svg
  Roomie/Roomie/Global/Resource/Assets.xcassets/icn/icn_detail_closed_40.imageset/Contents.json
  Roomie/Roomie/Global/Resource/Assets.xcassets/icn/icn_detail_closed_40.imageset/icn_detail_closed_40.svg
  Roomie/Roomie/Global/Resource/Assets.xcassets/icn/icn_in.imageset/Contents.json
  Roomie/Roomie/Global/Resource/Assets.xcassets/icn/icn_in.imageset/icn_in.svg
  Roomie/Roomie/Global/Resource/Assets.xcassets/icn/icn_likedlist_default.imageset/Contents.json
  Roomie/Roomie/Global/Resource/Assets.xcassets/icn/icn_likedlist_default.imageset/icn_likedlist_default.svg
  Roomie/Roomie/Global/Resource/Assets.xcassets/icn/icn_likedlist_pressed.imageset/Contents.json
  Roomie/Roomie/Global/Resource/Assets.xcassets/icn/icn_likedlist_pressed.imageset/icn_likedlist_pressed.svg
  Roomie/Roomie/Global/Resource/Assets.xcassets/icn/icn_search_40.imageset/Contents.json
  Roomie/Roomie/Global/Resource/Assets.xcassets/icn/icn_search_40.imageset/icn_search_40.svg
  Roomie/Roomie/Global/Utils/CancelBag.swift
  Roomie/Roomie/Presentation/Core/MainTabBarController.swift
  Roomie/Roomie/Presentation/Map/Model/MapModel.swift
  Roomie/Roomie/Presentation/Map/View/MapDetialCardView.swift
  Roomie/Roomie/Presentation/Map/View/MapView.swift
  Roomie/Roomie/Presentation/Map/ViewController/MapViewController.swift
  Roomie/Roomie/Presentation/Map/ViewModel/MapViewModel.swift
Labels: 🛠️ feat, 🎂 suyeon

#19 [feat/#16] 필터 뷰 세그먼트 컨트롤 구현 및 베이스파일 수정
  Roomie/Roomie/Global/Base/BaseView.swift
  Roomie/Roomie/Global/Base/BaseViewController.swift
  Roomie/Roomie/Global/Extensions/UITextField+.swift
  Roomie/Roomie/Presentation/Map/View/FilterPeriodView.swift
  Roomie/Roomie/Presentation/Map/View/FilterPriceView.swift
  Roomie/Roomie/Presentation/Map/View/FilterRoomView.swift
  Roomie/Roomie/Presentation/Map/View/FilterSegmentedControl.swift
  Roomie/Roomie/Presentation/Map/View/MapFilterView.swift
  Roomie/Roomie/Presentation/Map/View/MapView.swift
  Roomie/Roomie/Presentation/Map/ViewController/MapFilterViewController.swift
  Roomie/Roomie/Presentation/Map/ViewController/MapViewController.swift
Labels: ✂️ fix, 🛠️ feat, 🎂 suyeon

#21 [feat/#17] TourCheckView UI, CustomButton 구현
  Roomie/Roomie/Global/Components/CustomButton.swift
  Roomie/Roomie/Presentation/Tour/View/TourCheckView.swift
  Roomie/Roomie/Presentation/Tour/ViewController/TourCheckViewController.swift
Labels: 🛠️ feat, 🍩 seungwon

#23 [feat/#20] 필터 뷰 금액 UI 구현
  Roomie/Roomie/Global/Components/PriceSlider.swift
  Roomie/Roomie/Global/Components/PriceTextField.swift
  Roomie/Roomie/Global/Extensions/UITextField+.swift
  Roomie/Roomie/Presentation/Map/Model/MapModel.swift
  Roomie/Roomie/Presentation/Map/View/FilterPriceView.swift
  Roomie/Roomie/Presentation/Map/View/MapFilterView.swift
  Roomie/Roomie/Presentation/Map/ViewController/MapFilterViewController.swift
  Roomie/Roomie/Presentation/Map/ViewController/MapViewController.swift
  Roomie/Roomie/Presentation/Map/ViewModel/MapFilterViewModel.swift
Labels: 🛠️ feat, 🎂 suyeon

#26 [feat/#24] 필터 뷰 방 형태 UI 구현
  Roomie/Roomie/Global/Components/FilterOptionButton.swift
  Roomie/Roomie/Presentation/Map/View/FilterRoomView.swift
  Roomie/Roomie/Presentation/Map/ViewController/MapFilterViewController.swift
  Roomie/Roomie/Presentation/Map/ViewModel/MapFilterViewModel.swift
Labels: 🛠️ feat, 🎂 suyeon

#28 [feat/#22] TourUserView UI 구현
  Icon 
  Roomie/Roomie/Global/Components/DatePickerView.swift
  Roomie/Roomie/Global/Components/GenderButton.swift
  Roomie/Roomie/Global/Components/RoomieButton.swift
  Roomie/Roomie/Global/Components/TempComponents.swift
  Roomie/Roomie/Global/Components/TourTextField.swift
  Roomie/Roomie/Global/Enums/Gender.swift
  Roomie/Roomie/Global/Extensions/UIResponder+.swift
  Roomie/Roomie/Global/Protocol/KeyboardObservable.swift
  Roomie/Roomie/Presentation/Tour/View/TourCheckView.swift
  Roomie/Roomie/Presentation/Tour/View/TourUserView.swift
  Roomie/Roomie/Presentation/Tour/ViewController/TourCheckViewController.swift
  Roomie/Roomie/Presentation/Tour/ViewController/TourUserViewController.swift
  Roomie/Roomie/Presentation/Tour/ViewModel/TourViewModel.swift
Labels: 🛠️ feat, 🍩 seungwon

#29 [chore/#27] 공통 코드 수정
  Roomie/Roomie/Global/Base/BaseViewController.swift
  Roomie/Roomie/Global/Components/PriceTextField.swift
  Roomie/Roomie/Global/Enums/TempEnums.swift
  Roomie/Roomie/Presentation/Map/ViewController/MapViewController.swift
  Roomie/Roomie/Presentation/MapFilter/View/FilterPeriodView.swift
  Roomie/Roomie/Presentation/MapFilter/View/FilterPriceView.swift
  Roomie/Roomie/Presentation/MapFilter/View/FilterRoomView.swift
  Roomie/Roomie/Presentation/MapFilter/View/FilterSegmentedControl.swift
  Roomie/Roomie/Presentation/MapFilter/View/MapFilterView.swift
  Roomie/Roomie/Presentation/MapFilter/ViewController/MapFilterViewController.swift
  Roomie/Roomie/Presentation/MapFilter/ViewModel/MapFilterViewModel.swift
  Roomie/Roomie/Presentation/Tour/ViewController/TourCheckViewController.swift
  Roomie/Roomie/Presentation/Tour/ViewController/TourUserViewController.swift
Labels: 📎 chore, 🎂 suyeon

#32 [feat/#25] HomeView 상단 UI 구현
  Roomie/Roomie/Global/Components/MoodButtonView.swift
  Roomie/Roomie/Global/Components/UpdateButtonView.swift
  Roomie/Roomie/Global/Enums/MoodType.swift
  Roomie/Roomie/Presentation/Core/MainTabBarController.swift
  Roomie/Roomie/Presentation/Home/View/HomeView.swift
  Roomie/Roomie/Presentation/Home/ViewController/HomeViewController.swift
  Roomie/Roomie/Presentation/Map/View/MapView.swift
Labels: 🛠️ feat, 🍥 hyunsoo

#34 [feat/#31] 필터 뷰 계약기간 UI 구현
  Roomie/Roomie/Global/Components/DatePickerView.swift
  Roomie/Roomie/Presentation/MapFilter/View/FilterPeriodView.swift
  Roomie/Roomie/Presentation/MapFilter/ViewController/MapFilterViewController.swift
  Roomie/Roomie/Presentation/MapFilter/ViewModel/MapFilterViewModel.swift
Labels: 🛠️ feat, 🎂 suyeon

#36 [feat/#30] TourUserView 플로우, DatePickerView Protocol 구현
  Roomie/Roomie/Global/Components/DatePickerView.swift
  Roomie/Roomie/Global/Components/GenderButton.swift
  Roomie/Roomie/Global/Components/RoomieButton.swift
  Roomie/Roomie/Global/Components/TourTextField.swift
  Roomie/Roomie/Global/Enums/Gender.swift
  Roomie/Roomie/Presentation/Tour/View/TourUserView.swift
  Roomie/Roomie/Presentation/Tour/ViewController/TourCheckViewController.swift
  Roomie/Roomie/Presentation/Tour/ViewController/TourUserViewController.swift
  Roomie/Roomie/Presentation/Tour/ViewModel/TourViewModel.swift
Labels: 🛠️ feat, 🍩 seungwon

#38 [feat/#35] 필터 뷰 버튼 구현
  Roomie/Roomie/Presentation/MapFilter/View/MapFilterView.swift
  Roomie/Roomie/Presentation/MapFilter/ViewController/MapFilterViewController.swift
  Roomie/Roomie/Presentation/MapFilter/ViewModel/MapFilterViewModel.swift
Labels: 🛠️ feat, 🎂 suyeon

#40 [feat/#39] 필터 뷰 UI 완성
  Roomie/Roomie/Global/Components/DatePickerView.swift
  Roomie/Roomie/Global/Extensions/String+.swift
  Roomie/Roomie/Presentation/MapFilter/View/FilterPeriodView.swift
  Roomie/Roomie/Presentation/MapFilter/ViewController/MapFilterViewController.swift
  Roomie/Roomie/Presentation/MapFilter/ViewModel/MapFilterViewModel.swift
Labels: 🛠️ feat, 🎂 suyeon

#45 [feat/#37] TourFlow구현
  Roomie/Roomie/Global/Components/OtherButton.swift
  Roomie/Roomie/Global/Components/TourTextView.swift
  Roomie/Roomie/Global/Extensions/UITextView+.swift
  Roomie/Roomie/Presentation/Tour/View/TourCompleteView.swift
  Roomie/Roomie/Presentation/Tour/View/TourDateView.swift
  Roomie/Roomie/Presentation/Tour/ViewController/TourCheckViewController.swift
  Roomie/Roomie/Presentation/Tour/ViewController/TourCompleteViewController.swift
  Roomie/Roomie/Presentation/Tour/ViewController/TourDateViewController.swift
  Roomie/Roomie/Presentation/Tour/ViewController/TourUserViewController.swift
  Roomie/Roomie/Presentation/Tour/ViewModel/TourCheckViewModel.swift
  Roomie/Roomie/Presentation/Tour/ViewModel/TourDateViewModel.swift
  Roomie/Roomie/Presentation/Tour/ViewModel/TourUserViewModel.swift
Labels: 🛠️ feat, 🍞 seungwon

#47 [feat/#41] 지도 검색 뷰 구현
  Roomie/Roomie/Global/Components/MapTextField.swift
  Roomie/Roomie/Presentation/Map/View/MapView.swift
  Roomie/Roomie/Presentation/Map/ViewController/MapViewController.swift
  Roomie/Roomie/Presentation/MapSearch/Model/MapSearchModel.swift
  Roomie/Roomie/Presentation/MapSearch/View/MapSearchCollectionViewCell.swift
  Roomie/Roomie/Presentation/MapSearch/View/MapSearchView.swift
  Roomie/Roomie/Presentation/MapSearch/ViewController/MapSearchViewController.swift
  Roomie/Roomie/Presentation/MapSearch/ViewModel/MapSearchViewModel.swift
Labels: 🛠️ feat, 🎂 suyeon

#50 [feat/#48] 바텀시트 뷰 구현 및 공통 컴포넌트 제작
  Roomie/Roomie/Global/Components/RoomListCollectionViewCell.swift
  Roomie/Roomie/Global/Components/RoomieIconButton.swift
  Roomie/Roomie/Global/Components/RoomieWhiteButton.swift
  Roomie/Roomie/Presentation/Home/ViewController/HomeViewController.swift
  Roomie/Roomie/Presentation/Map/Model/MapModel.swift
  Roomie/Roomie/Presentation/Map/View/MapListSheetView.swift
  Roomie/Roomie/Presentation/Map/View/MapView.swift
  Roomie/Roomie/Presentation/Map/ViewController/MapListSheetViewController.swift
  Roomie/Roomie/Presentation/Map/ViewController/MapViewController.swift
  Roomie/Roomie/Presentation/Map/ViewModel/MapViewModel.swift
  Roomie/Roomie/Presentation/MapFilter/View/MapFilterView.swift
Labels: 🛠️ feat, 🎂 suyeon

#58 [chore/#57] myPage, wishList 연결
  Roomie/Roomie/Global/Components/MoodButtonView.swift
  Roomie/Roomie/Presentation/Home/ViewController/HomeViewController.swift
  Roomie/Roomie/Presentation/MyPage/ViewController/MyPageViewController.swift
Labels: 📎 chore, 🍥 hyunsoo

#59 [feat/#46] 상세매물 section1, 2 구현
  Roomie/Roomie/Global/Components/HouseInfoIconLabel.swift
  Roomie/Roomie/Global/Components/LookInsidePhotoButton.swift
  Roomie/Roomie/Presentation/HouseDetail/Helper/HouseDetailLayoutHelper.swift
  Roomie/Roomie/Presentation/HouseDetail/Model/HouseDetailModel.swift
  Roomie/Roomie/Presentation/HouseDetail/View/Cell/HouseInfoCell.swift
  Roomie/Roomie/Presentation/HouseDetail/View/Cell/HousePhotoCell.swift
  Roomie/Roomie/Presentation/HouseDetail/View/HouseDetailView.swift
  Roomie/Roomie/Presentation/HouseDetail/ViewController/HouseDetailViewController.swift
  Roomie/Roomie/Presentation/HouseDetail/ViewModel/HouseDetailViewModel.swift
Labels: 🛠️ feat, 🍞 seungwon

#60 [feat/#55] 지도 검색 및 바텀시트 엠티 뷰 구현
  Roomie/Roomie/Global/Resource/Assets.xcassets/img/img_emptyview.imageset/Contents.json
  Roomie/Roomie/Global/Resource/Assets.xcassets/img/img_emptyview.imageset/img_emptyview.png
  Roomie/Roomie/Global/Resource/Assets.xcassets/img/img_emptyview.imageset/img_emptyview@2x.png
  Roomie/Roomie/Global/Resource/Assets.xcassets/img/img_emptyview.imageset/img_emptyview@3x.png
  Roomie/Roomie/Presentation/Map/View/MapListSheetEmptyView.swift
  Roomie/Roomie/Presentation/Map/View/MapListSheetView.swift
  Roomie/Roomie/Presentation/Map/ViewController/MapListSheetViewController.swift
  Roomie/Roomie/Presentation/MapSearch/View/MapSearchEmptyView.swift
  Roomie/Roomie/Presentation/MapSearch/View/MapSearchView.swift
  Roomie/Roomie/Presentation/MapSearch/ViewController/MapSearchViewController.swift
  Roomie/Roomie/Presentation/MapSearch/ViewModel/MapSearchViewModel.swift
Labels: 🛠️ feat, 🎂 suyeon

#64 [chore/#43] 그라데이션 및 homeViewUI userName 수정
  Roomie/Roomie/Global/Enums/Gradient.swift
  Roomie/Roomie/Global/Extensions/CAGradientLayer+.swift
  Roomie/Roomie/Global/Extensions/UIColor+.swift
  Roomie/Roomie/Global/Extensions/UIView+.swift
  Roomie/Roomie/Presentation/Home/View/HomeView.swift
  Roomie/Roomie/Presentation/Home/ViewController/HomeViewController.swift
  Roomie/Roomie/Presentation/MoodList/Model/MoodListModel.swift
  Roomie/Roomie/Presentation/MoodList/View/MoodListCollectionHeaderView.swift
  Roomie/Roomie/Presentation/MoodList/ViewController/MoodListViewController.swift
Labels: 📎 chore, 🍥 hyunsoo

#65 [feat/#18] 토스트 유틸 코드 구현
  Roomie/Roomie/Global/Resource/Colors.xcassets/transparent/transp_gray11_80.colorset/Contents.json
  Roomie/Roomie/Global/Utils/Toast.swift
Labels: 🛠️ feat, 🎂 suyeon

#68 [feat/#61] HouseDetail Section3(RoomMood) UI 구현
  Roomie/Roomie/Global/Components/CheckIconLabel.swift
  Roomie/Roomie/Global/Components/HouseInfoIconLabel.swift
  Roomie/Roomie/Global/Components/MoodTagView.swift
  Roomie/Roomie/Global/Enums/MoodType.swift
  Roomie/Roomie/Presentation/HouseDetail/Helper/HouseDetailLayoutHelper.swift
  Roomie/Roomie/Presentation/HouseDetail/View/Cell/HouseDetailHeaderView.swift
  Roomie/Roomie/Presentation/HouseDetail/View/Cell/RoomMoodCell.swift
  Roomie/Roomie/Presentation/HouseDetail/View/HouseDetailView.swift
  Roomie/Roomie/Presentation/HouseDetail/ViewController/HouseDetailViewController.swift
  Roomie/Roomie/Presentation/HouseDetail/ViewModel/HouseDetailViewModel.swift
Labels: 🛠️ feat, 🍞 seungwon

#73 [feat/#49] 투어플로우 GUI
  Roomie/Roomie/Global/Resource/Assets.xcassets/img/img_gomi_excited.imageset/Contents.json
  Roomie/Roomie/Global/Resource/Assets.xcassets/img/img_gomi_excited.imageset/gomi_excited.png
  Roomie/Roomie/Global/Resource/Assets.xcassets/img/img_gomi_excited.imageset/gomi_excited@2x.png
  Roomie/Roomie/Global/Resource/Assets.xcassets/img/img_gomi_excited.imageset/gomi_excited@3x.png
  Roomie/Roomie/Presentation/Tour/View/TourCompleteView.swift
  Roomie/Roomie/Presentation/Tour/ViewController/TourCheckViewController.swift
  Roomie/Roomie/Presentation/Tour/ViewController/TourCompleteViewController.swift
  Roomie/Roomie/Presentation/Tour/ViewController/TourDateViewController.swift
  Roomie/Roomie/Presentation/Tour/ViewController/TourUserViewController.swift
Labels: 🛠️ feat, 🧤 refactor, 🍞 seungwon

#74 [feat/#71] 디자인 명세 수정사항 반영
  Roomie/Roomie/Presentation/Map/ViewController/MapViewController.swift
  Roomie/Roomie/Presentation/MapFilter/View/FilterPriceView.swift
  Roomie/Roomie/Presentation/MapFilter/ViewController/MapFilterViewController.swift
  Roomie/Roomie/Presentation/MapFilter/ViewModel/MapFilterViewModel.swift
Labels: 🛠️ feat, 🎂 suyeon

#76 [feat/#72] 상세 매물 페이지 section 4 구현
  Roomie/Roomie/Presentation/HouseDetail/Component/RoomStatusView.swift
  Roomie/Roomie/Presentation/HouseDetail/Helper/HouseDetailLayoutHelper.swift
  Roomie/Roomie/Presentation/HouseDetail/Model/HouseDetailModel.swift
  Roomie/Roomie/Presentation/HouseDetail/View/Cell/HouseInfoCollectionViewCell.swift
  Roomie/Roomie/Presentation/HouseDetail/View/Cell/RoomStatusCollectionViewCell.swift
  Roomie/Roomie/Presentation/HouseDetail/View/HouseDetailView.swift
  Roomie/Roomie/Presentation/HouseDetail/ViewController/HouseDetailViewController.swift
  Roomie/Roomie/Presentation/HouseDetail/ViewModel/HouseDetailViewModel.swift
Labels: 🛠️ feat, 🍞 seungwon

#78 [feat/#70] empty view UI 구현
  Roomie/Roomie/Global/Extensions/UIView+.swift
  Roomie/Roomie/Global/Resource/Assets.xcassets/img/img_calm.imageset/Contents.json
  Roomie/Roomie/Global/Resource/Assets.xcassets/img/img_calm.imageset/calm_img_i.png
  Roomie/Roomie/Global/Resource/Assets.xcassets/img/img_clean.imageset/Contents.json
  Roomie/Roomie/Global/Resource/Assets.xcassets/img/img_clean.imageset/clean_img_i.png
  Roomie/Roomie/Global/Resource/Assets.xcassets/img/img_exciting.imageset/Contents.json
  Roomie/Roomie/Global/Resource/Assets.xcassets/img/img_exciting.imageset/exciting_img_i.png
  Roomie/Roomie/Global/Resource/Assets.xcassets/img/img_home_gomi.imageset/Contents.json
  Roomie/Roomie/Global/Resource/Assets.xcassets/img/img_home_gomi.imageset/home-character1.png
  Roomie/Roomie/Global/Resource/Assets.xcassets/img/img_moodview_calm.imageset/Contents.json
  Roomie/Roomie/Global/Resource/Assets.xcassets/img/img_moodview_calm.imageset/img_moodview_clam.png
  Roomie/Roomie/Global/Resource/Assets.xcassets/img/img_moodview_clean.imageset/Contents.json
  Roomie/Roomie/Global/Resource/Assets.xcassets/img/img_moodview_clean.imageset/img_moodview_clean.png
  Roomie/Roomie/Global/Resource/Assets.xcassets/img/img_moodview_exciting.imageset/Contents.json
  Roomie/Roomie/Global/Resource/Assets.xcassets/img/img_moodview_exciting.imageset/img_moodview_exciting.png
  Roomie/Roomie/Global/Resource/Assets.xcassets/img/img_sweat_gomi.imageset/Contents.json
  Roomie/Roomie/Global/Resource/Assets.xcassets/img/img_sweat_gomi.imageset/img_sweat_gomi.png
  Roomie/Roomie/Presentation/Home/View/HomeEmptyView.swift
  Roomie/Roomie/Presentation/Home/View/HomeView.swift
  Roomie/Roomie/Presentation/Home/ViewController/HomeViewController.swift
  Roomie/Roomie/Presentation/MyPage/ViewController/MyPageViewController.swift
  Roomie/Roomie/Presentation/WishList/View/WishListEmptyView.swift
  Roomie/Roomie/Presentation/WishList/View/WishListView.swift
  Roomie/Roomie/Presentation/WishList/ViewController/WishListViewController.swift
  Roomie/Roomie/Presentation/WishList/ViewModel/WishListViewModel.swift
Labels: 🛠️ feat, 🍥 hyunsoo

#79 [feat/#66] home view 커스텀 네비바UI 구현
  Roomie/Roomie/Global/Base/BaseViewController.swift
  Roomie/Roomie/Global/Extensions/CAGradientLayer+.swift
  Roomie/Roomie/Presentation/Home/Model/HomeModel.swift
  Roomie/Roomie/Presentation/Home/View/HomeView.swift
  Roomie/Roomie/Presentation/Home/ViewController/HomeViewController.swift
Labels: 📎 chore, 🍥 hyunsoo

#83 [refactor/#82] 매물 상세 페이지 section 1, 2, 3 리팩토링
  Roomie/Roomie/Presentation/Home/ViewController/HomeViewController.swift
  Roomie/Roomie/Presentation/HouseDetail/Component/HouseMoodTagView.swift
  Roomie/Roomie/Presentation/HouseDetail/Helper/HouseDetailLayoutHelper.swift
  Roomie/Roomie/Presentation/HouseDetail/View/HouseDetailView.swift
  Roomie/Roomie/Presentation/HouseDetail/ViewController/HouseDetailViewController.swift
Labels: 🧤 refactor, 🍞 seungwon

#85 [refactor/#84] 매물 상세 페이지 입주현황 TableView 구현
  Roomie/Roomie/Presentation/HouseDetail/View/Cell/RoomStatusTableViewCell.swift
  Roomie/Roomie/Presentation/HouseDetail/View/HouseDetailView.swift
  Roomie/Roomie/Presentation/HouseDetail/ViewController/HouseDetailViewController.swift
Labels: 🛠️ feat, 🧤 refactor, 🍞 seungwon

#87 [feat/#75] 네트워크 세팅 및 지도 검색 API 구현
  Roomie/Roomie/Global/Info.plist
  Roomie/Roomie/Network/Base/Environment.swift
  Roomie/Roomie/Network/Base/ModelType.swift
  Roomie/Roomie/Network/Base/MoyaLoggingPlugin.swift
  Roomie/Roomie/Network/DTO/BaseDTO/BaseResponseBody.swift
  Roomie/Roomie/Network/DTO/Empty/EmptyDTO.swift
  Roomie/Roomie/Network/DTO/Maps/MapRequestDTO.swift
  Roomie/Roomie/Network/DTO/Maps/MapResponseDTO.swift
  Roomie/Roomie/Network/DTO/Maps/MapSearchResponseDTO.swift
  Roomie/Roomie/Network/DTO/Users/MyPageResponseDTO.swift
  Roomie/Roomie/Network/Service/MapsService.swift
  Roomie/Roomie/Network/TargetType/MapsTargetType.swift
  Roomie/Roomie/Presentation/Map/ViewController/MapViewController.swift
  Roomie/Roomie/Presentation/MapSearch/Model/MapSearchModel.swift
  Roomie/Roomie/Presentation/MapSearch/ServiceProtocol/MapSearchServiceProtocol.swift
  Roomie/Roomie/Presentation/MapSearch/View/MapSearchCollectionViewCell.swift
  Roomie/Roomie/Presentation/MapSearch/ViewController/MapSearchViewController.swift
  Roomie/Roomie/Presentation/MapSearch/ViewModel/MapSearchViewModel.swift
Labels: 🛠️ feat, 🎂 suyeon

#89 [feat/#86] 매물 상세 페이지 expendView 구현
  Roomie/Roomie/Presentation/HouseDetail/Component/HouseFacilityView.swift
  Roomie/Roomie/Presentation/HouseDetail/View/HouseDetailView.swift
  Roomie/Roomie/Presentation/HouseDetail/ViewController/HouseDetailViewController.swift
Labels: 🛠️ feat, 🍞 seungwon

#91 [feat/#90] 상세 매물 페이지 룸메이트 섹션 구현
  Roomie/Roomie/Presentation/HouseDetail/View/Cell/HouseDetailHeaderView.swift
  Roomie/Roomie/Presentation/HouseDetail/View/Cell/HouseInfoCollectionViewCell.swift
  Roomie/Roomie/Presentation/HouseDetail/View/Cell/HousePhotoCollectionViewCell.swift
  Roomie/Roomie/Presentation/HouseDetail/View/Cell/RoomMoodCollectionViewCell.swift
  Roomie/Roomie/Presentation/HouseDetail/View/Cell/RoommateNotFoundTableViewCell.swift
  Roomie/Roomie/Presentation/HouseDetail/View/Cell/RoommateTableViewCell.swift
  Roomie/Roomie/Presentation/HouseDetail/View/HouseDetailView.swift
  Roomie/Roomie/Presentation/HouseDetail/ViewController/HouseDetailViewController.swift
Labels: 🛠️ feat, 🍞 seungwon

#93 [refactor/#80] Home,WishList,MoodList mvvm으로 리팩토링
  Roomie/Roomie/Global/Base/BaseViewController.swift
  Roomie/Roomie/Global/Components/HouseListCollectionViewCell.swift
  Roomie/Roomie/Global/Enums/MoodType.swift
  Roomie/Roomie/Presentation/Home/Component/AppleLoverClub.swift
  Roomie/Roomie/Presentation/Home/Model/HomeModel.swift
  Roomie/Roomie/Presentation/Home/View/HomeView.swift
  Roomie/Roomie/Presentation/Home/ViewController/HomeViewController.swift
  Roomie/Roomie/Presentation/Home/ViewModel/HomeViewModel.swift
  Roomie/Roomie/Presentation/MoodList/Model/MoodListModel.swift
  Roomie/Roomie/Presentation/MoodList/ViewController/MoodListViewController.swift
  Roomie/Roomie/Presentation/MoodList/ViewModel/MoodListViewModel.swift
  Roomie/Roomie/Presentation/WishList/Model/WishListModel.swift
  Roomie/Roomie/Presentation/WishList/ViewController/WishListViewController.swift
  Roomie/Roomie/Presentation/WishList/ViewModel/WishListViewModel.swift
Labels: 🧤 refactor, 🍥 hyunsoo

#95 [feat/#92] 상세 매물 네비게이션바, bottomButton 구현
  Roomie/Roomie/Global/Components/RoomieIconButton.swift
  Roomie/Roomie/Presentation/HouseDetail/Helper/HouseDetailLayoutHelper.swift
  Roomie/Roomie/Presentation/HouseDetail/View/HouseDetailView.swift
  Roomie/Roomie/Presentation/HouseDetail/ViewController/HouseDetailViewController.swift
  Roomie/Roomie/Presentation/HouseDetail/ViewModel/HouseDetailViewModel.swift
Labels: 🛠️ feat, 🍞 seungwon

#97 [feat/#96] 매물 상세 페이지 Bottom Sheet UI 구현
  Roomie/Roomie/Presentation/HouseDetail/Component/HouseInfoIconLabel.swift
  Roomie/Roomie/Presentation/HouseDetail/Component/RoomTourButton.swift
  Roomie/Roomie/Presentation/HouseDetail/View/HouseDetailSheetView.swift
  Roomie/Roomie/Presentation/HouseDetail/View/HouseDetailView.swift
  Roomie/Roomie/Presentation/HouseDetail/ViewController/HouseDetailSheetViewController.swift
  Roomie/Roomie/Presentation/HouseDetail/ViewController/HouseDetailViewController.swift
  Roomie/Roomie/Presentation/HouseDetail/ViewModel/HouseDetailViewModel.swift
Labels: 🛠️ feat, 🍞 seungwon

#99 [feat/#94] HomeAPI 구현
  Roomie/Roomie/Network/DTO/Users/HomeResponseDTO.swift
  Roomie/Roomie/Network/Service/UserService.swift
  Roomie/Roomie/Network/TargetType/UserTargetType.swift
  Roomie/Roomie/Presentation/Core/MainTabBarController.swift
  Roomie/Roomie/Presentation/Home/ServiceProtocol/HomeServiceProtocol.swift
  Roomie/Roomie/Presentation/Home/View/HomeView.swift
  Roomie/Roomie/Presentation/Home/ViewController/HomeViewController.swift
  Roomie/Roomie/Presentation/Home/ViewModel/HomeViewModel.swift
Labels: 🛠️ feat, 🍥 hyunsoo

#101 [feat/#88] 지도 매물 조회 API 구현
  Roomie/Roomie/Global/Base/BaseViewController.swift
  Roomie/Roomie/Global/Components/DatePickerView.swift
  Roomie/Roomie/Global/Components/HouseListCollectionViewCell.swift
  Roomie/Roomie/Global/Extensions/String+.swift
  Roomie/Roomie/Network/DTO/Maps/MapRequestDTO.swift
  Roomie/Roomie/Network/DTO/Maps/MapResponseDTO.swift
  Roomie/Roomie/Network/Service/MapsService.swift
  Roomie/Roomie/Network/TargetType/MapsTargetType.swift
  Roomie/Roomie/Presentation/Core/MainTabBarController.swift
  Roomie/Roomie/Presentation/Map/Model/MapModel.swift
  Roomie/Roomie/Presentation/Map/Model/MarkerDetailInfo.swift
  Roomie/Roomie/Presentation/Map/Model/MarkerInfo.swift
  Roomie/Roomie/Presentation/Map/ServiceProtocol/MapServiceProtocol.swift
  Roomie/Roomie/Presentation/Map/ViewController/MapListSheetViewController.swift
  Roomie/Roomie/Presentation/Map/ViewController/MapViewController.swift
  Roomie/Roomie/Presentation/Map/ViewModel/MapViewModel.swift
  Roomie/Roomie/Presentation/MapFilter/Model/MapRequestModelBuilder.swift
  Roomie/Roomie/Presentation/MapFilter/ViewController/MapFilterViewController.swift
  Roomie/Roomie/Presentation/MapFilter/ViewModel/MapFilterViewModel.swift
  Roomie/Roomie/Presentation/MapSearch/View/MapSearchCollectionViewCell.swift
  Roomie/Roomie/Presentation/MapSearch/ViewController/MapSearchViewController.swift
  Roomie/Roomie/Presentation/MapSearch/ViewModel/MapSearchViewModel.swift
Labels: 🛠️ feat, 🎂 suyeon

#103 [feat/#100] 찜리스트 API 구현
  Roomie/Roomie/Global/Components/HouseListCollectionViewCell.swift
  Roomie/Roomie/Network/DTO/Houses/WishListResponseDTO.swift
  Roomie/Roomie/Network/Service/HousesService.swift
  Roomie/Roomie/Network/TargetType/HousesTargetType.swift
  Roomie/Roomie/Presentation/Home/Model/HomeModel.swift
  Roomie/Roomie/Presentation/Home/Model/RecentlyHouseInfo.swift
  Roomie/Roomie/Presentation/Home/Model/UserInfo.swift
  Roomie/Roomie/Presentation/Home/View/HomeView.swift
  Roomie/Roomie/Presentation/Home/ViewController/HomeViewController.swift
  Roomie/Roomie/Presentation/MyPage/ViewController/MyPageViewController.swift
  Roomie/Roomie/Presentation/WishList/Model/WishListModel.swift
  Roomie/Roomie/Presentation/WishList/ServiceProtocol/WishListServiceProtocol.swift
  Roomie/Roomie/Presentation/WishList/ViewController/WishListViewController.swift
  Roomie/Roomie/Presentation/WishList/ViewModel/WishListViewModel.swift
Labels: 🛠️ feat, 🍥 hyunsoo

#105 [feat/#98] 상세 매물 이미지 페이지 UI 구현
  Roomie/Roomie/Presentation/HouseDetail/Component/HouseFacilityExpandView.swift
  Roomie/Roomie/Presentation/HouseDetail/Component/HouseInnerPhotoButton.swift
  Roomie/Roomie/Presentation/HouseDetail/Component/RoomFacilityExpandView.swift
  Roomie/Roomie/Presentation/HouseDetail/Model/RoomDetail.swift
  Roomie/Roomie/Presentation/HouseDetail/View/HouseAllPhotoView.swift
  Roomie/Roomie/Presentation/HouseDetail/View/HouseDetailView.swift
  Roomie/Roomie/Presentation/HouseDetail/View/HouseSinglePhotoView.swift
  Roomie/Roomie/Presentation/HouseDetail/ViewController/HouseAllPhotoViewController.swift
  Roomie/Roomie/Presentation/HouseDetail/ViewController/HouseDetailSheetViewController.swift
  Roomie/Roomie/Presentation/HouseDetail/ViewController/HouseDetailViewController.swift
  Roomie/Roomie/Presentation/HouseDetail/ViewController/HouseSinglePhotoViewController.swift
Labels: 🛠️ feat, 🍞 seungwon

#107 [feat/#104] 분위기별 리스트 DTO 구현
  Roomie/Roomie/Network/DTO/Houses/MoodListRequestDTO.swift
  Roomie/Roomie/Network/DTO/Houses/MoodListResponseDTO.swift
Labels: 🛠️ feat, 🍥 hyunsoo

#108 [feat/#106] HouseDetailTargetType 분위기별 방 보기 추가
  Roomie/Roomie/Network/DTO/HouseDetails/HouseDetailResponseDTO.swift
  Roomie/Roomie/Network/TargetType/HousesTargetType.swift
  Roomie/Roomie/Presentation/HouseDetail/Model/HouseDetailModel.swift
  Roomie/Roomie/Presentation/HouseDetail/ServiceProtocol/HouseDetailServiceProtocol.swift
Labels: 🛠️ feat, 🍞 seungwon

#111 [feat/#110] HousesService 구현
  Roomie/Roomie/Network/DTO/Houses/MoodListRequestDTO.swift
  Roomie/Roomie/Network/Service/HousesService.swift
  Roomie/Roomie/Presentation/HouseDetail/ServiceProtocol/HouseDetailServiceProtocol.swift
  Roomie/Roomie/Presentation/MoodList/ServiceProtocol/MoodListServiceProtocol.swift
Labels: 🛠️ feat, 🍞 seungwon

#113 [feat/#102] 마이페이지 API 구현
  Roomie/Roomie/Global/Base/BaseViewController.swift
  Roomie/Roomie/Network/Service/UserService.swift
  Roomie/Roomie/Network/TargetType/UserTargetType.swift
  Roomie/Roomie/Presentation/Core/MainTabBarController.swift
  Roomie/Roomie/Presentation/MyPage/ServiceProtocol/MyPageServiceProtocol.swift
  Roomie/Roomie/Presentation/MyPage/View/Cell/MyPagePlusHeaderView.swift
  Roomie/Roomie/Presentation/MyPage/ViewController/MyPageViewController.swift
  Roomie/Roomie/Presentation/MyPage/ViewModel/MyPageViewModel.swift
Labels: 🛠️ feat, 🎂 suyeon

#115 [feat/#109] MoodList API 구현
  Roomie/Roomie/Global/Components/HouseListCollectionViewCell.swift
  Roomie/Roomie/Global/Enums/MoodType.swift
  Roomie/Roomie/Network/DTO/Houses/MoodListResponseDTO.swift
  Roomie/Roomie/Network/Service/HousesService.swift
  Roomie/Roomie/Presentation/Home/Model/RecentlyHouseInfo.swift
  Roomie/Roomie/Presentation/Home/ViewController/HomeViewController.swift
  Roomie/Roomie/Presentation/Home/ViewModel/HomeViewModel.swift
  Roomie/Roomie/Presentation/MoodList/Model/MoodListModel.swift
  Roomie/Roomie/Presentation/MoodList/ViewController/MoodListViewController.swift
  Roomie/Roomie/Presentation/MoodList/ViewModel/MoodListViewModel.swift
  Roomie/Roomie/Presentation/WishList/Model/WishListModel.swift
  Roomie/Roomie/Presentation/WishList/ViewController/WishListViewController.swift
  Roomie/Roomie/Presentation/WishList/ViewModel/WishListViewModel.swift
Labels: 🛠️ feat, 🍥 hyunsoo

#118 [feat/#116] 찜 버튼 TargetType, DTO 구현
  Roomie/Roomie/Network/TargetType/HousesTargetType.swift
Labels: 🛠️ feat, 🍥 hyunsoo

#120 [fix/#119] 타겟타입 분리
  Roomie/Roomie/Global/Components/VersionFooterView.swift
  Roomie/Roomie/Network/DTO/BaseDTO/BaseResponseBody.swift
  Roomie/Roomie/Network/Service/HomeService.swift
  Roomie/Roomie/Network/Service/HousesService.swift
  Roomie/Roomie/Network/Service/MapsService.swift
  Roomie/Roomie/Network/Service/MyPageService.swift
  Roomie/Roomie/Network/TargetType/HomeTargetType.swift
  Roomie/Roomie/Network/TargetType/HousesTargetType.swift
  Roomie/Roomie/Network/TargetType/MapsTargetType.swift
  Roomie/Roomie/Network/TargetType/MyPageTargetType.swift
  Roomie/Roomie/Presentation/Core/MainTabBarController.swift
  Roomie/Roomie/Presentation/Home/ServiceProtocol/HomeServiceProtocol.swift
  Roomie/Roomie/Presentation/HouseDetail/ServiceProtocol/HouseDetailServiceProtocol.swift
  Roomie/Roomie/Presentation/Map/ServiceProtocol/MapServiceProtocol.swift
  Roomie/Roomie/Presentation/MoodList/ServiceProtocol/MoodListServiceProtocol.swift
  Roomie/Roomie/Presentation/WishList/ServiceProtocol/WishListServiceProtocol.swift
Labels: ✂️ fix, 🎂 suyeon

#122 [feat/#81] home view UI detail 잡기
  Roomie/Roomie/Presentation/Home/View/HomeView.swift
  Roomie/Roomie/Presentation/Home/ViewController/HomeViewController.swift
Labels: 📎 chore, 🍥 hyunsoo

#124 [feat/#114] 지도 디테일 구현
  Roomie/Roomie/Presentation/Map/View/MapView.swift
  Roomie/Roomie/Presentation/Map/ViewController/MapViewController.swift
  Roomie/Roomie/Presentation/MapSearch/ViewController/MapSearchViewController.swift
  Roomie/Roomie/Presentation/MyPage/ViewController/MyPageViewController.swift
Labels: 🛠️ feat, 🎂 suyeon

#128 [feat/#125] 지도 뷰 디테일 구현 및 장소 초기화 기능 추가
  Roomie/Roomie/Global/Components/RoomieIconButton.swift
  Roomie/Roomie/Presentation/Map/View/MapView.swift
  Roomie/Roomie/Presentation/Map/ViewController/MapListSheetViewController.swift
  Roomie/Roomie/Presentation/Map/ViewController/MapViewController.swift
  Roomie/Roomie/Presentation/Map/ViewModel/MapViewModel.swift
Labels: 🛠️ feat, 🎂 suyeon

#130 [feat/#127] 매물 상세 -> 투어 플로우 네비게이션 연결
  Roomie/Roomie/Presentation/Home/ViewController/HomeViewController.swift
  Roomie/Roomie/Presentation/HouseDetail/Component/RoomTourButton.swift
  Roomie/Roomie/Presentation/HouseDetail/Model/RoomButtonInfo.swift
  Roomie/Roomie/Presentation/HouseDetail/View/HouseAllPhotoView.swift
  Roomie/Roomie/Presentation/HouseDetail/View/HouseDetailSheetView.swift
  Roomie/Roomie/Presentation/HouseDetail/ViewController/HouseDetailSheetViewController.swift
  Roomie/Roomie/Presentation/HouseDetail/ViewController/HouseDetailViewController.swift
  Roomie/Roomie/Presentation/HouseDetail/ViewController/HouseSinglePhotoViewController.swift
  Roomie/Roomie/Presentation/HouseDetail/ViewModel/HouseDetailViewModel.swift
Labels: 🛠️ feat, 🍞 seungwon

#131 [feat/#123] wishList, homeView 찜 버튼 API 구현
  Roomie/Roomie/Global/Components/HouseListCollectionViewCell.swift
  Roomie/Roomie/Global/Utils/Toast.swift
  Roomie/Roomie/Network/DTO/Houses/MoodListResponseDTO.swift
  Roomie/Roomie/Network/DTO/Houses/PinnedResponseDTO.swift
  Roomie/Roomie/Network/DTO/Houses/WishListResponseDTO.swift
  Roomie/Roomie/Network/DTO/Maps/MapResponseDTO.swift
  Roomie/Roomie/Network/DTO/Users/HomeResponseDTO.swift
  Roomie/Roomie/Network/Service/HomeService.swift
  Roomie/Roomie/Network/Service/HousesService.swift
  Roomie/Roomie/Presentation/Home/ServiceProtocol/HomeServiceProtocol.swift
  Roomie/Roomie/Presentation/Home/ViewController/HomeViewController.swift
  Roomie/Roomie/Presentation/Home/ViewModel/HomeViewModel.swift
  Roomie/Roomie/Presentation/MoodList/ServiceProtocol/MoodListServiceProtocol.swift
  Roomie/Roomie/Presentation/WishList/ServiceProtocol/WishListServiceProtocol.swift
  Roomie/Roomie/Presentation/WishList/ViewController/WishListViewController.swift
  Roomie/Roomie/Presentation/WishList/ViewModel/WishListViewModel.swift
Labels: 🛠️ feat, 🍥 hyunsoo

#135 [feat/#134] 홈뷰, 찜리스트뷰 상세 매물 페이지
  Roomie/Roomie/Presentation/Home/ViewController/HomeViewController.swift
  Roomie/Roomie/Presentation/Home/ViewModel/HomeViewModel.swift
  Roomie/Roomie/Presentation/WishList/ViewController/WishListViewController.swift
  Roomie/Roomie/Presentation/WishList/ViewModel/WishListViewModel.swift
Labels: 🛠️ feat, 🍥 hyunsoo

#137 [chore/#136] 홈뷰, 찜리스트뷰 상세매물페이지 연결 코드리뷰 반영 수정
  Roomie/Roomie/Presentation/Home/ViewController/HomeViewController.swift
  Roomie/Roomie/Presentation/Home/ViewModel/HomeViewModel.swift
  Roomie/Roomie/Presentation/WishList/View/WishListView.swift
  Roomie/Roomie/Presentation/WishList/ViewController/WishListViewController.swift
  Roomie/Roomie/Presentation/WishList/ViewModel/WishListViewModel.swift
Labels: 📎 chore, 🍥 hyunsoo

#138 [feat/#129] 찜 API 구현 및 화면 전환
  Roomie/Roomie/Network/Service/MapsService.swift
  Roomie/Roomie/Presentation/Home/ViewController/HomeViewController.swift
  Roomie/Roomie/Presentation/Home/ViewModel/HomeViewModel.swift
  Roomie/Roomie/Presentation/Map/ServiceProtocol/MapServiceProtocol.swift
  Roomie/Roomie/Presentation/Map/ViewController/MapListSheetViewController.swift
  Roomie/Roomie/Presentation/Map/ViewController/MapViewController.swift
  Roomie/Roomie/Presentation/Map/ViewModel/MapViewModel.swift
  Roomie/Roomie/Presentation/WishList/ViewController/WishListViewController.swift
  Roomie/Roomie/Presentation/WishList/ViewModel/WishListViewModel.swift
Labels: 🛠️ feat, 🎂 suyeon

#140 [feat/#133] 투어 신청 플로우 API 연동, 이후 네비게이션 연결
  Roomie/Roomie/Global/Components/DatePickerView.swift
  Roomie/Roomie/Network/DTO/Houses/TourRequestDTO.swift
  Roomie/Roomie/Network/DTO/Houses/TourResponseDTO.swift
  Roomie/Roomie/Network/Service/HousesService.swift
  Roomie/Roomie/Network/TargetType/HousesTargetType.swift
  Roomie/Roomie/Network/TargetType/MapsTargetType.swift
  Roomie/Roomie/Presentation/HouseDetail/Component/RoomFacilityExpandView.swift
  Roomie/Roomie/Presentation/HouseDetail/Model/SelectedRoomInfo.swift
  Roomie/Roomie/Presentation/HouseDetail/ServiceProtocol/HouseDetailServiceProtocol.swift
  Roomie/Roomie/Presentation/HouseDetail/View/Cell/RoomStatusTableViewCell.swift
  Roomie/Roomie/Presentation/HouseDetail/View/HouseDetailSheetView.swift
  Roomie/Roomie/Presentation/HouseDetail/View/HouseDetailView.swift
  Roomie/Roomie/Presentation/HouseDetail/ViewController/HouseAllPhotoViewController.swift
  Roomie/Roomie/Presentation/HouseDetail/ViewController/HouseDetailSheetViewController.swift
  Roomie/Roomie/Presentation/HouseDetail/ViewController/HouseDetailViewController.swift
  Roomie/Roomie/Presentation/HouseDetail/ViewController/HouseSinglePhotoViewController.swift
  Roomie/Roomie/Presentation/HouseDetail/ViewModel/HouseDetailViewModel.swift
  Roomie/Roomie/Presentation/Tour/Component/TourTextView.swift
  Roomie/Roomie/Presentation/Tour/Model/TourRequestModelBuilder.swift
  Roomie/Roomie/Presentation/Tour/View/TourUserView.swift
  Roomie/Roomie/Presentation/Tour/ViewController/TourCheckViewController.swift
  Roomie/Roomie/Presentation/Tour/ViewController/TourCompleteViewController.swift
  Roomie/Roomie/Presentation/Tour/ViewController/TourDateViewController.swift
  Roomie/Roomie/Presentation/Tour/ViewController/TourUserViewController.swift
  Roomie/Roomie/Presentation/Tour/ViewModel/TourCheckViewModel.swift
  Roomie/Roomie/Presentation/Tour/ViewModel/TourDateViewModel.swift
  Roomie/Roomie/Presentation/Tour/ViewModel/TourUserViewModel.swift
Labels: 🛠️ feat, 🍞 seungwon

#142 [feat/#139] 서비스 분리 및 찜 API 구현 및 화면 연결
  Roomie/Roomie/Network/Service/HousesService.swift
  Roomie/Roomie/Network/Service/MoodListService.swift
  Roomie/Roomie/Network/Service/WishListService.swift
  Roomie/Roomie/Network/TargetType/HousesTargetType.swift
  Roomie/Roomie/Network/TargetType/MoodListTargetType.swift
  Roomie/Roomie/Network/TargetType/WishListTargetType.swift
  Roomie/Roomie/Presentation/Home/ViewController/HomeViewController.swift
  Roomie/Roomie/Presentation/MoodList/ViewController/MoodListViewController.swift
  Roomie/Roomie/Presentation/MoodList/ViewModel/MoodListViewModel.swift
  Roomie/Roomie/Presentation/MyPage/ViewController/MyPageViewController.swift
Labels: 🛠️ feat, 🎂 suyeon

#143 [feat/#132] 홈뷰 웹뷰 연결
  Roomie/Roomie/Presentation/Home/Component/AppleLoverClub.swift
  Roomie/Roomie/Presentation/Home/ViewController/APPLELOVERCLUBViewController.swift
  Roomie/Roomie/Presentation/Home/ViewController/HomeViewController.swift
Labels: 🛠️ feat, 🍥 hyunsoo

#145 [feat/#144] 카드 뷰와 매물 상세 뷰 화면 연결
  Roomie/Roomie/Presentation/Map/View/MapDetialCardView.swift
  Roomie/Roomie/Presentation/Map/ViewController/MapViewController.swift
Labels: 🛠️ feat, 🎂 suyeon

#148 [feat/#146] 앱 아이콘 및 스플래쉬 추가
  Roomie/Roomie/Global/Base.lproj/LaunchScreen.storyboard
  Roomie/Roomie/Global/Resource/Assets.xcassets/AppIcon.appiconset/Contents.json
  Roomie/Roomie/Global/Resource/Assets.xcassets/AppIcon.appiconset/app_icon.png
  Roomie/Roomie/Global/Resource/Assets.xcassets/img/img_splash.imageset/Contents.json
  Roomie/Roomie/Global/Resource/Assets.xcassets/img/img_splash.imageset/img_splash.png
Labels: 🛠️ feat, 🎂 suyeon

#150 [fix] 투어 신청 플로우 후 네비게이션 제스처 오류 수정
  Roomie/Roomie/Presentation/MoodList/ViewController/MoodListViewController.swift
  Roomie/Roomie/Presentation/Tour/ViewController/TourCompleteViewController.swift
  Roomie/Roomie/Presentation/WishList/ViewController/WishListViewController.swift
Labels: ✂️ fix, 🍞 seungwon
