Repository WeAreRoommies/Roomie-iOS, pull requests merged in 2025-05, with the labels that each got.

#162 [refactor/#161] 상세 매물 페이지 수정 사항 반영
  Roomie/Roomie/Network/Service/HomeService.swift
  Roomie/Roomie/Network/Service/HousesService.swift
  Roomie/Roomie/Presentation/Core/MainTabBarController.swift
  Roomie/Roomie/Presentation/Home/ViewController/HomeViewController.swift
  Roomie/Roomie/Presentation/HouseDetail/Model/RoommateInfo.swift
  Roomie/Roomie/Presentation/HouseDetail/View/Cell/RoomStatusTableViewCell.swift
  Roomie/Roomie/Presentation/HouseDetail/View/Cell/RoommateNotFoundTableViewCell.swift
  Roomie/Roomie/Presentation/HouseDetail/View/Cell/RoommateTableViewCell.swift
  Roomie/Roomie/Presentation/HouseDetail/View/HouseDetailView.swift
  Roomie/Roomie/Presentation/HouseDetail/ViewController/HouseDetailViewController.swift
  Roomie/Roomie/Presentation/HouseDetail/ViewModel/HouseDetailViewModel.swift
Labels: 🧤 refactor, 🍞 seungwon

#163 [feat/#158] 온보딩 뷰 UI 및 뷰 연결
  Roomie/Roomie/Application/SceneDelegate.swift
  Roomie/Roomie/Global/Enums/MoodType.swift
  Roomie/Roomie/Global/Enums/OnBoardingType.swift
  Roomie/Roomie/Global/Extensions/UIFont+.swift
  Roomie/Roomie/Global/Extensions/UIImage+.swift
  Roomie/Roomie/Global/Resource/Assets.xcassets/icn/icn_apple_logo.imageset/Contents.json
  Roomie/Roomie/Global/Resource/Assets.xcassets/icn/icn_apple_logo.imageset/icn_apple_logo.png
  Roomie/Roomie/Global/Resource/Assets.xcassets/icn/icn_kakao_logo.imageset/Contents.json
  Roomie/Roomie/Global/Resource/Assets.xcassets/icn/icn_kakao_logo.imageset/icn_kakao_logo.png
  Roomie/Roomie/Global/Resource/Assets.xcassets/img/img_apple_login.imageset/Contents.json
  Roomie/Roomie/Global/Resource/Assets.xcassets/img/img_apple_login.imageset/img_apple_login.png
  Roomie/Roomie/Global/Resource/Assets.xcassets/img/img_kakao_login.imageset/Contents.json
  Roomie/Roomie/Global/Resource/Assets.xcassets/img/img_kakao_login.imageset/img_kakao_login.png
  Roomie/Roomie/Presentation/MoodList/ViewController/MoodListViewController.swift
  Roomie/Roomie/Presentation/OnBoarding/View/LoginView.swift
  Roomie/Roomie/Presentation/OnBoarding/View/OnBoardingStepView.swift
  Roomie/Roomie/Presentation/OnBoarding/ViewController/LoginViewController.swift
  Roomie/Roomie/Presentation/OnBoarding/ViewController/OnBoardingViewController.swift
  Roomie/Roomie/Presentation/WishList/View/WishListView.swift
Labels: 🛠️ feat, 🍥 hyunsoo

#175 [feat/#168] 필터 뷰 스프린트 변경사항 반영
  Roomie/Roomie/Network/DTO/Maps/MapRequestDTO.swift
  Roomie/Roomie/Network/DTO/Maps/MapResponseDTO.swift
  Roomie/Roomie/Network/Service/MapsService.swift
  Roomie/Roomie/Presentation/Map/ViewModel/MapViewModel.swift
  Roomie/Roomie/Presentation/MapFilter/Model/MapRequestModelBuilder.swift
  Roomie/Roomie/Presentation/MapFilter/View/FilterRoomView.swift
  Roomie/Roomie/Presentation/MapFilter/ViewController/MapFilterViewController.swift
  Roomie/Roomie/Presentation/MapFilter/ViewModel/MapFilterViewModel.swift
Labels: 🛠️ feat, 🎂 suyeon

#176 [feat/#169] 마이페이지 구조 변경
  Roomie/Roomie/Network/DTO/Users/MyPageResponseDTO.swift
  Roomie/Roomie/Network/Service/MyPageService.swift
  Roomie/Roomie/Presentation/MyPage/Component/MyPageButton.swift
  Roomie/Roomie/Presentation/MyPage/Helper/MyPageLayoutHelper.swift
  Roomie/Roomie/Presentation/MyPage/Model/MyPageModel.swift
  Roomie/Roomie/Presentation/MyPage/View/Cell/MyPageCollectionViewCell.swift
  Roomie/Roomie/Presentation/MyPage/View/Cell/MyPageServiceHeaderView.swift
  Roomie/Roomie/Presentation/MyPage/View/MyPageHeaderView.swift
  Roomie/Roomie/Presentation/MyPage/View/MyPageView.swift
  Roomie/Roomie/Presentation/MyPage/ViewController/MyPageViewController.swift
  Roomie/Roomie/Presentation/MyPage/ViewModel/MyPageViewModel.swift
Labels: 🛠️ feat, 🎂 suyeon
