Repository WeAreRoommies/Roomie-iOS, pull requests merged in 2025-07, with the labels that each got.

#193 [refactor/#192] 매물상세페이지 DTO수정
  Roomie/Roomie/Network/DTO/Houses/HouseDetailResponseDTO.swift
  Roomie/Roomie/Network/Service/HousesService.swift
  Roomie/Roomie/Presentation/HouseDetail/Model/RoomInfo.swift
  Roomie/Roomie/Presentation/HouseDetail/ViewController/HouseDetailViewController.swift
  Roomie/Roomie/Presentation/HouseDetail/ViewModel/HouseDetailViewModel.swift
Labels: 🧤 refactor, 🍞 seungwon

#195 [feat/#178] 지도 뷰 스프린트 변경사항 반영
  Roomie/Roomie/Global/Resource/Assets.xcassets/icn/btn_circle_active.imageset/Contents.json
  Roomie/Roomie/Global/Resource/Assets.xcassets/icn/btn_circle_active.imageset/btn_full_active.svg
  Roomie/Roomie/Global/Resource/Assets.xcassets/icn/btn_circle_default.imageset/Contents.json
  Roomie/Roomie/Global/Resource/Assets.xcassets/icn/btn_circle_default.imageset/btn_full_default.svg
  Roomie/Roomie/Global/Resource/Assets.xcassets/icn/btn_heart_40_active.imageset/Contents.json
  Roomie/Roomie/Global/Resource/Assets.xcassets/icn/btn_heart_40_active.imageset/btn_heart_40_active.svg
  Roomie/Roomie/Global/Resource/Assets.xcassets/icn/btn_heart_40_normal.imageset/Contents.json
  Roomie/Roomie/Global/Resource/Assets.xcassets/icn/btn_heart_40_normal.imageset/btn_heart_40_normal.svg
  Roomie/Roomie/Global/Resource/Assets.xcassets/icn/icn_full_pin_active.imageset/Contents.json
  Roomie/Roomie/Global/Resource/Assets.xcassets/icn/icn_full_pin_active.imageset/btn_full_pin_active.png
  Roomie/Roomie/Global/Resource/Assets.xcassets/icn/icn_full_pin_active.imageset/btn_full_pin_active@2x.png
  Roomie/Roomie/Global/Resource/Assets.xcassets/icn/icn_full_pin_active.imageset/btn_full_pin_active@3x.png
  Roomie/Roomie/Global/Resource/Assets.xcassets/icn/icn_full_pin_normal.imageset/Contents.json
  Roomie/Roomie/Global/Resource/Assets.xcassets/icn/icn_full_pin_normal.imageset/btn_full_pin_normal.png
  Roomie/Roomie/Global/Resource/Assets.xcassets/icn/icn_full_pin_normal.imageset/btn_full_pin_normal@2x.png
  Roomie/Roomie/Global/Resource/Assets.xcassets/icn/icn_full_pin_normal.imageset/btn_full_pin_normal@3x.png
  Roomie/Roomie/Network/DTO/Maps/MapRequestDTO.swift
  Roomie/Roomie/Network/DTO/Maps/MapResponseDTO.swift
  Roomie/Roomie/Network/DTO/Maps/MapSearchResponseDTO.swift
  Roomie/Roomie/Network/Service/HomeService.swift
  Roomie/Roomie/Network/Service/MapsService.swift
  Roomie/Roomie/Network/TargetType/HomeTargetType.swift
  Roomie/Roomie/Presentation/Home/ServiceProtocol/HomeServiceProtocol.swift
  Roomie/Roomie/Presentation/Home/ViewController/HomeViewController.swift
  Roomie/Roomie/Presentation/Home/ViewController/LocationSearchViewController.swift
  Roomie/Roomie/Presentation/Home/ViewModel/HomeViewModel.swift
  Roomie/Roomie/Presentation/Map/Model/MarkerInfo.swift
  Roomie/Roomie/Presentation/Map/View/MapDetialCardView.swift
  Roomie/Roomie/Presentation/Map/View/MapListSheetView.swift
  Roomie/Roomie/Presentation/Map/ViewController/MapListSheetViewController.swift
  Roomie/Roomie/Presentation/Map/ViewController/MapViewController.swift
  Roomie/Roomie/Presentation/Map/ViewModel/MapViewModel.swift
  Roomie/Roomie/Presentation/MapFilter/Model/MapRequestModelBuilder.swift
  Roomie/Roomie/Presentation/MapSearch/Model/AddressInfo.swift
  Roomie/Roomie/Presentation/MapSearch/ViewController/MapSearchViewController.swift
  Roomie/Roomie/Presentation/MapSearch/ViewModel/MapSearchViewModel.swift
Labels: 🛠️ feat, 🎂 suyeon

#200 [chore/#170] 온보딩 뷰 스와이프 제스처 수정
  Roomie/Roomie/Presentation/OnBoarding/ViewController/LoginViewController.swift
  Roomie/Roomie/Presentation/OnBoarding/ViewController/OnBoardingViewController.swift
Labels: 📎 chore, 🍥 hyunsoo

#205 [feat/#185] 로그아웃, 탈퇴 구현
  Roomie/Roomie/Global/Base/BaseViewController.swift
  Roomie/Roomie/Global/Enums/AlertType.swift
  Roomie/Roomie/Global/Utils/AlertManager.swift
  Roomie/Roomie/Network/Service/MyAccountService.swift
  Roomie/Roomie/Network/TargetType/MyAccountTargetType.swift
  Roomie/Roomie/Presentation/MyAccount/ServiceProtocol/MyAccountServiceProtocol.swift
  Roomie/Roomie/Presentation/MyAccount/ViewController/MyAccountViewController.swift
  Roomie/Roomie/Presentation/MyAccount/ViewModel/MyAccountViewModel.swift
Labels: 🛠️ feat, 🍞 seungwon

#207 [setting/#206] 앱 아이콘 변경
  Roomie/Roomie/Global/Resource/Assets.xcassets/AppIcon.appiconset/Contents.json
  Roomie/Roomie/Global/Resource/Assets.xcassets/AppIcon.appiconset/app_icon.png
  Roomie/Roomie/Global/Resource/Assets.xcassets/AppIcon.appiconset/logo.png
Labels: 🧾 setting, 🎂 suyeon

#210 [feat/#203] 마이페이지 웹뷰 연결
  Roomie/Roomie/Global/Enums/WebViewType.swift
  Roomie/Roomie/Presentation/MyPage/View/MyPageView.swift
  Roomie/Roomie/Presentation/MyPage/ViewController/MyPageViewController.swift
  Roomie/Roomie/Presentation/MyPage/ViewController/MyPageWebViewController.swift
Labels: 🛠️ feat, 🎂 suyeon
